### ISSUE TITLE
Rover: sound messed up

### ISSUE THREAD

**Issue by davecparker** [davecparker/mars-app#105]
Rover sound does not sound right, especially when releasing and coasting.

**Comment by MichaelFriebel** [comment]
All sound issues from the coding side should now be fixed with the following actions:

— Replaced anonymous functions used with game.playSound() to prevent
audio from overlapping
— Replaced audio.isChannelPlaying() with audio.isChannelActive() to
address inconsistencies in playback
— Referenced acceleration audio channels to rover wheel speed for
deceleration-to-acceleration continuity
