### ISSUE TITLE
Rover: Need crater elevation terrain

### ISSUE THREAD

**Issue by davecparker** [davecparker/mars-app#149]
Driving into a crater should make elevation change

**Comment by davecparker** [comment]
Mike can decide if we are doing a simple version of crater terrain or not.

**Comment by MichaelFriebel** [comment]
We have crater elevation terrain as of pull request #187.

I will open new issues for the following:
- Incorrect crater terrain generation for courses originating from within craters
- Occasionally unrealistic obstacle placement on crater terrain

A future enhancement could be to allow the scroll-view to also scroll vertically so that larger elevation deviations, and therefore larger craters, could be depicted. As it is, crater terrain is limited to the dimensions of the scroll-view when actual Martian craters would proportionally greatly exceed those dimensions. Automatically scaling the scroll-view contents for a zooming-out effect to accommodate larger craters as needed may be an alternative or additional method.
